#! /bin/sh


xsetroot -cursor_name left_ptr &

if xrandr -q | grep 'HDMI-1 connected'; then

bspc monitor eDP-1 -d I IV V VII
bspc monitor HDMI-1 -d  II III VI VIII
xrandr --output HDMI-1 --mode 1366x768 --left-of eDP-1
else
bspc monitor eDP-1 -d I II III IV V VI VII VIII
fi
xrandr --output eDP-1 --mode 1366x768

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.


feh --bg-fill /home/lucio/Pictures/d.jpg
/home/lucio/.config/polybar/./launch.sh --shades
picom --experimental-backends &
bspc config border_width 0
polychromatic-cli -o brightness -p 0
